module pom update .
meveo-org/meveo pull request #725
Opened 2023-05-30 18:20 UTC by masumcse1

Few changes has made for module pom file. 

deleted - <dependencyManagement> tag
deleted - wildfly-jakartaee8 ,wildfly-feature-pack  dependency 
added   -dependencies tagd
added new dependency -- <artifactId>jakarta.jakartaee-api</artifactId>

2023-05-30 21:49 UTC, smichea requested changes

2023-05-30 21:49 UTC, smichea commented on meveo-admin-ejbs/src/main/java/org/meveo/service/config/impl/MavenConfigurationService.java
> +		githubRepo.setName("sebastien michea");
```suggestion
		githubRepo.setName("meveo github");
```

2023-05-31 11:25 UTC, masumcse1 commented on meveo-admin-ejbs/src/main/java/org/meveo/service/config/impl/MavenConfigurationService.java
> +		githubRepo.setName("sebastien michea");
I have updated this change.

2023-06-05 21:57 UTC, smichea approved these changes

2023-06-05 21:57 UTC, merged